GET http://localhost:8080/api/creators
Accept: application/json

###

POST http://localhost:8080/api/creators
Content-Type: application/json

    {"name": "creator1",
      "ssn": "DFG133"}
###

POST http://localhost:8080/api/creators/1/recipes
Content-Type: application/json

{"name": "recipe1",
"description":  "desc1"}
###

POST http://localhost:8080/api/creators/1/recipes
Content-Type: application/json

{"name": "recipe2",
  "description":  "desc2"}
###

POST http://localhost:8080/api/creators
Content-Type: application/json

{"name": "creator2",
"ssn": "485KSI"
}

###
PUT http://localhost:8080/api/creators/1
Content-Type: application/json

{"name": "creator1",
  "ssn": "777SSS"
}

###
DELETE http://localhost:8080/api/creators/1
Content-Type: application/json

###
