GET http://localhost:8080/api/recipes
Accept: application/json

###

POST http://localhost:8080/api/recipes
Content-Type: application/json

{
  "name": "recipe1",
  "description": "leiras1"
}
###

POST http://localhost:8080/api/recipes
Content-Type: application/json

{
  "name": "recipe2",
  "description": "leiras2"
}

###
PUT http://localhost:8080/api/recipes/1
Content-Type: application/json

{
  "name": "ing12",
  "description": "KG"
}

###
DELETE http://localhost:8080/api/recipes/1
Content-Type: application/json

###