version: '3'

services:
  recipes-mariadb:
    image: mariadb
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: recipes
      MYSQL_USER: recipes
      MYSQL_PASSWORD: recipes
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  recipes-app:
    image: recipes
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - recipes-mariadb
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mariadb://recipes-mariadb/recipes'
    entrypoint: ['./wait-for-it.sh', '-t', '120','recipes-mariadb:3306','--','java','org.springframework.boot.loader.JarLauncher']